USE bar;
-- MySQL Script generated by MySQL Workbench
-- Wed Oct 27 23:35:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bar` DEFAULT CHARACTER SET utf8 ;
USE `bar` ;

-- -----------------------------------------------------
-- Table `bar`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bar`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(55) NOT NULL,
  `apellido` VARCHAR(55) NOT NULL,
  `telefono` VARCHAR(30) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bar`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bar`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(55) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `FK_Usuario_Cliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `FK_Usuario_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bar`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bar`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bar`.`Reservas` (
  `idReservas` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `cantidadPersonas` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idReservas`),
  INDEX `FK_Reservas_Cliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `FK_Reservas_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bar`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bar`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bar`.`Productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stockMin` INT NOT NULL,
  `stockMax` INT NOT NULL,
  `stockAct` INT NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bar`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bar`.`Pedidos` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `idPedido` INT NOT NULL,
  PRIMARY KEY (`idPedidos`),
  INDEX `FK_Pedidos_Cliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `FK_Pedidos_Productos_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `FK_Pedidos_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bar`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Pedidos_Productos`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bar`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bar`.`MetodoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bar`.`MetodoPago` (
  `idMetodoPago` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMetodoPago`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
